// Auto-generated from live v6 reference. Do not edit by hand.
export const GEN_V6_BUILTIN_VARS: Record<string, string> = {
	ask: '""',
	bar_index: '""',
	bid: '""',
	close: '""',
	dayofmonth: '""',
	dayofweek: '""',
	high: '""',
	hl2: '""',
	hlc3: '""',
	hlcc4: '""',
	hour: '""',
	last_bar_index: '""',
	last_bar_time: '""',
	low: '""',
	minute: '""',
	month: '""',
	na: '""',
	ohlc4: '""',
	open: '""',
	second: '""',
	time: '""',
	time_close: '""',
	time_tradingday: '""',
	timenow: '""',
	volume: '""',
	weekofyear: '""',
	year: '""',
};
