allowBuilds:
  '@vscode/vsce-sign': true
  esbuild: true
  keytar: true
  puppeteer: true
minimumReleaseAgeExclude:
  - '@types/node@26.0.1'
onlyBuiltDependencies:
  - '@vscode/vsce-sign'
  - esbuild
  - keytar
  - puppeteer
