//@version=6
indicator("Bk2", overlay = true)
import HeWhoMustNotBeNamed/customcandles/2 as ca
ohlcSource = input.string('ma', 'src', options = ['regular', 'ma'])
highSource = high
lowSource = low
if ohlcSource == 'ma'
    [mo, mh, ml, mc] = ca.macandles('sma', 10)
    highSource := mh
    lowSource := ml
score() =>
    s = 0
    for bar = bar_index - 10 to bar_index by 1
        if highSource[bar_index - bar] > lowSource[bar_index - bar]
            s := s + 1
    s
control = close > open ? ta.sma(close, 5) : 0.0
x = 0
for i = 0 to 2 by 1
    x := score()
plot(x + control)
