//@version=6
indicator("Bk3", overlay = true)
import HeWhoMustNotBeNamed/zigzag/5 as zg
highSource = high
lowSource = low
[zp, zpb, zpd, zpr, zo, zod, ztb, zdv, np, dp] = zg.czigzag(5, 34, highSource, lowSource)
score(barArray) =>
    s = 0
    minBar = array.min(barArray)
    for bar = minBar to bar_index by 1
        if high[bar_index - bar] > low[bar_index - bar]
            s := s + 1
    s
control = close > open ? ta.sma(close, 5) : 0.0
x = 0
for i = 0 to 2 by 1
    x := score(zpb)
plot(x + control)
